# Site settings
title: The bed with two wrong sides
email: twowrongsides@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Responding to malcontent with misanthropy
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.thebedwithtwowrongsides.com" # the base hostname & protocol for your site
twitter_username: jdrennison
permalink:    /:year/:month/:day/:title/
paginate: 5
owner:
  name:           JD Rennison
  avatar:         avatar.jpg
  email:          twowrongsides@gmail.com

# Build settings
timezone:    Europe/London
future:      true
highlighter:    true
markdown: kramdown
